### ISSUE TITLE
Loading pretrained model in main_discover?

### ISSUE THREAD

**Issue by haoranD** [muliyangm/ComEx#1]
Hi,

Many thanks for your excellent work.

May I ask where you load the pretrained checkpoint in main_discorver.py?

Thanks for your assistance.

**Comment by muliyangm** [comment]
Hi there,

Thanks for your interest in our work! 

It turns out that I had mistakenly removed the code for loading checkpoint during the code cleaning, and I have just added it back. Sorry for the inconvenience.

Please let me know if you have any more questions!

**Comment by haoranD** [comment]
> Hi there,
> 
> Thanks for your interest in our work!
> 
> It turns out that I had mistakenly removed the code for loading checkpoint during the code cleaning, and I have just added it back. Sorry for the inconvenience.
> 
> Please let me know if you have any more questions!

thanks a lot
